<?php

use PHPUnit\Framework\TestCase;

class BCryptTest extends TestCase
{
    public function testHashReturnsString()
    {
        $bcrypt = new BCrypt();
        $hash = $bcrypt->hash('test123');
        $this->assertIsString($hash);
        $this->assertGreaterThan(50, strlen($hash));
    }

    public function testVerifyCorrectPassword()
    {
        $bcrypt = new BCrypt();
        $hash = $bcrypt->hash('mypassword');
        $this->assertTrue($bcrypt->verify('mypassword', $hash));
    }

    public function testVerifyWrongPassword()
    {
        $bcrypt = new BCrypt();
        $hash = $bcrypt->hash('mypassword');
        $this->assertFalse($bcrypt->verify('wrongpassword', $hash));
    }

    public function testVerifyLegacyHash()
    {
        // Legacy $2a$ hash generated by old BCrypt class
        $bcrypt = new BCrypt();
        $legacyHash = '$2a$13$SBy5MgSuvGXwHkLSP7VuGuoCXR3JhOoFs3wR/9RdL1KSoflBUlh1G';
        $this->assertTrue($bcrypt->verify('test123', $legacyHash));
    }
}
